<?xml version="1.0"?>

<robot name="limo_ackerman" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:include filename="$(find limo_description)/urdf/limo_xacro.xacro" />
    <xacro:include filename="$(find limo_description)/urdf/limo_steering_hinge.xacro" />
    <xacro:include filename="$(find limo_description)/urdf/limo_ackerman.gazebo" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <xacro:property name="wheelbase" value="0.2"/>
    <xacro:property name="track" value="0.14"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />
    <xacro:property name="base_mass" value="2.1557"/>

    <xacro:property name="wheel_length" value="0.0437" />
    <xacro:property name="wheel_radius" value="0.048" />

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 -0.15" rpy="0 0 0"/>
    </joint>

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
            <geometry>
                <mesh filename="package://limo_description/meshes/limo_base.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
            <geometry>
                <mesh filename="package://limo_description/meshes/limo_collision.stl"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" />
            <mass value="${base_mass}" />
            <inertia ixx="0.019264" ixy="0" ixz="0" 
                     iyy="0.029586" iyz="0" 
                     izz="0.02693" />
        </inertial>
    </link>

    <xacro:limo_laser parent_prefix="base_link" frame_prefix="laser">
        <origin xyz="0.103 0 -0.034" rpy="0 0 0"/>
    </xacro:limo_laser>

    <xacro:limo_depth_camera parent_prefix="base_link" frame_prefix="depth_camera">
        <origin xyz="0.084 0 0.03" rpy="0 0 0"/>
    </xacro:limo_depth_camera>

    <xacro:limo_imu parent_prefix="base_link" frame_prefix="imu">
        <origin xyz="0.0 0 -0.1" rpy="0 0 0"/>
    </xacro:limo_imu>
    
    <xacro:limo_left_steering_hinge parent_prefix="base_link" wheel_prefix="left_steering_hinge">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0  0" />
    </xacro:limo_left_steering_hinge>

    <xacro:limo_right_steering_hinge parent_prefix="base_link" wheel_prefix="right_steering_hinge">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_right_steering_hinge>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_left" reflect="1">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_right" reflect="-1">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>
</robot>
