topics:
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 10
- name    : gazebo
  topic   : dummy_twist
  timeout : 0.5
  priority: 1
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 2
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255